language: node_js
node_js:
  - "lts/*"
  - "node"
script:
  - npm run test
  - npm run coverage
  - npm run doc
  - mkdir .public
  - cp -r doc/generated/@pikselpalette/sequoia-js-client-sdk/*/* .public
deploy:
  local-dir: './.public'
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
